// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"module4/conf"
	"module4/data"
)

// Injectors from wire.go:

func Initialize() *data.MyDB {
	viper := conf.NewConfiure()
	myDB := data.NewMyDB(viper)
	return myDB
}
